server:
  port: 9191
spring:
  application:
    name: order-service
  cloud:
    config:
      uri: http://localhost:9091
---
spring:
  profiles: prod
  cloud:
    config:
      uri: http://cloud-config-server:9091